description: default config for binary CIFAR10 classification
logger:
  entity: dalmiaman
  project: test-lightning

trainer:
  batch_size: 8
  epochs: 1
  params:
    gpus:
      - 0
    row_log_interval: 1

module:
  name: binary-classification
  config:
    optimizer:
      name: SGD
      args:
        lr: 0.001
        momentum: 0.9
        nesterov: true
      scheduler:
        interval: epoch
        monitor: loss
        name: ReduceLROnPlateau
        params:
            mode: 'min'
            factor: 0.1
            patience: 5
            verbose: true
            threshold: 0.0001
            threshold_mode: abs
    loss:
      train:
        name: binary-cross-entropy
        params:
            reduction: none
      val:
        name: binary-cross-entropy
        params:
            reduction: none
    classes:
      - 0
      - 1
    save:
      period: 1
      monitor: val_loss
      verbose: true
      mode: min
      save_weights_only: true
    load:
      version: null
      epoch: -1
      load_best: False
      resume_optimizer: False

    network:
      config:
        - name: Conv2d
          params:
            in_channels: 3
            out_channels: 64
            kernel_size: 3
        - name: BatchNorm2d
          params:
            num_features: 64
        - name: ReLU
          params: {}
        - name: Conv2d
          params:
            in_channels: 64
            out_channels: 64
            kernel_size: 3
        - name: BatchNorm2d
          params:
            num_features: 64
        - name: ReLU
          params: {}
        - name: AdaptiveAvgPool2d
          params:
            output_size:
            - 1
            - 1
        - name: Flatten
          params: {}
        - name: Linear
          params:
            in_features: 64
            out_features: 64
        - name: ReLU
          params: {}
        - name: Linear
          params:
            in_features: 64
            out_features: 1
data:
  data_type: image
  target_transform:
    name: classification
    params:
      classes:
        - 0
        - 1
  signal_transform:
    train:
    - name: Permute
      params:
        order:
          - 2
          - 0
          - 1
    val:
    - name: Permute
      params:
        order:
          - 2
          - 0
          - 1

    test:
    - name: Permute
      params:
        order:
          - 2
          - 0
          - 1
  dataset:
    name: classification_dataset
    config:
      - name: CIFAR10
        version: binary
    params: {}
  collate_fn:
    name: classification_collate
    params: {}
