description: default config for CIFAR10 classification with resnet18
metrics_to_track:
- accuracy
entity: dalmiaman
project: cifar10
train_mode: train-val
val_mode: test

model:
    name: multiclass-classification
    batch_size: 512
    epochs: 35
    optimizer:
      name: AdamW
      args:
        lr: 0.00012
        weight_decay: 0.4
      scheduler:
        name: 1cycle
        update: batch
        params:
            max_lr: 0.003
            epochs: 35
            steps_per_epoch: 98
            pct_start: 0.3
            div_factor: 25
    loss:
      train-val:
        name: cross-entropy
        params:
            reduction: none
      test:
        name: cross-entropy
        params:
            reduction: none
    classes:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
    save:
      period: 2
      monitor: accuracy
      monitor_mode: max
    load:
      version: null
      epoch: -1
      load_best: False
      resume_optimizer: False

network:
    name: neural_net
    params:
        config:
        - name: resnet18
          params:
            in_channels: 3
            pretrained: true
        - name: AdaptiveAvgPool2d
          params:
            output_size:
            - 1
            - 1
        - name: Flatten
          params: {}
        - name: Linear
          params:
            in_features: 512
            out_features: 10

data:
  data_type: image
  target_transform:
    name: classification
    params:
      classes:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
  signal_transform:
    train-val:
    - name: Permute
      params:
        order:
          - 2
          - 0
          - 1
    - name: Rescale
      params:
        value: 255.
    - name: RandomHorizontalFlip
      params:
        p: 0.5
    - name: RandomCrop
      params:
        padding: 4
        size:
          - 32
          - 32
        padding_mode: reflect
    - name: Normalize
      params:
        mean: cifar
        std: cifar

    test:
    - name: Permute
      params:
        order:
          - 2
          - 0
          - 1
    - name: Rescale
      params:
        value: 255.
    - name: RandomHorizontalFlip
      params:
        p: 0.5
    - name: RandomCrop
      params:
        padding: 4
        size:
          - 32
          - 32
        padding_mode: reflect
    - name: Normalize
      params:
        mean: cifar
        std: cifar

  dataset:
    name: classification_dataset
    config:
      - name: CIFAR10
        version: default
    params: {}
  collate_fn:
    name: classification_collate
    params: {}

description: default config for CIFAR10 classification with resnet18
logger:
  entity: dalmiaman
  project: test-lightning

trainer:
  batch_size: 64
  params:
    gpus:
      - 0
    max_epochs: 100
    weights_summary: full

module:
  name: binary-classification
  config:
    # optimization
    optimizer:
      name: SGD
      args:
        lr: 0.001
        momentum: 0.9
        nesterov: true
      scheduler:
        name: StepLR
        init_params:
            gamma: 0.9
            step_size: 1
        opt_params:
          interval: epoch

    # loss function
    loss:
      train:
        name: binary-cross-entropy
        params:
            reduction: none
      val:
        name: binary-cross-entropy
        params:
            reduction: none
      test:
        name: binary-cross-entropy
        params:
            reduction: none

    # meta
    classes:
      - 0
      - 1

    # model checkpoint
    checkpoint:
      period: 1
      monitor: loss
      verbose: true
      mode: min
      save_weights_only: false
      save_top_k: -1

    # resuming model checkpoint
    # TODO
    load:
      version: null
      epoch: -1
      load_best: False
      resume_optimizer: False

    # evaluation
    eval:
      maximize_metric: specificity

    # neural net architecture
    network:
      config:
        - name: Conv2d
          params:
            in_channels: 3
            out_channels: 64
            kernel_size: 3
        - name: BatchNorm2d
          params:
            num_features: 64
        - name: ReLU
          params: {}
        - name: Conv2d
          params:
            in_channels: 64
            out_channels: 64
            kernel_size: 3
        - name: BatchNorm2d
          params:
            num_features: 64
        - name: ReLU
          params: {}
        - name: AdaptiveAvgPool2d
          params:
            output_size:
            - 1
            - 1
        - name: Flatten
          params: {}
        - name: Linear
          params:
            in_features: 64
            out_features: 64
        - name: ReLU
          params: {}
        - name: Linear
          params:
            in_features: 64
            out_features: 1
data:
  data_type: image
  target_transform:
    name: classification
    params:
      classes:
        - 0
        - 1
  signal_transform:
    train:
    - name: Permute
      params:
        order:
          - 2
          - 0
          - 1
    val:
    - name: Permute
      params:
        order:
          - 2
          - 0
          - 1

    test:
    - name: Permute
      params:
        order:
          - 2
          - 0
          - 1
  dataset:
    name: classification_dataset
    config:
      - name: CIFAR10
        version: binary
    params: {}
  collate_fn:
    name: classification_collate
    params: {}

