description: default config for CIFAR10 classification with resnet18
logger:
  entity: dalmiaman
  project: test-lightning

modes:
  train_mode: train-val
  val_mode: test
  test_mode: test

trainer:
  batch_size: 512
  params:
    gpus:
      - 0
    max_epochs: 35
    weights_summary: full

module:
  name: multiclass-classification
  config:
    # optimization
    optimizer:
      name: AdamW
      args:
        lr: 0.00012
        weight_decay: 0.4
      scheduler:
        scheduler:
        name: 1cycle
        init_params:
            max_lr: 0.003
            epochs: 35
            steps_per_epoch: 98
            pct_start: 0.3
            div_factor: 25
        opt_params:
          interval: batch

    # loss function
    loss:
      train-val:
        name: cross-entropy
        params:
            reduction: none
      val:
        name: cross-entropy
        params:
            reduction: none
      test:
        name: cross-entropy
        params:
            reduction: none

    # meta
    classes:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9

    # model checkpoint
    checkpoint:
      period: 1
      monitor: loss
      verbose: true
      mode: min
      save_weights_only: false
      save_top_k: -1

    # resuming model checkpoint
    # TODO
    load:
      version: null
      epoch: -1
      load_best: False
      resume_optimizer: False

    # evaluation
    eval:
      maximize_metric: specificity

    # neural net architecture
    network:
      config:
        - name: resnet18
          params:
            in_channels: 3
            pretrained: true
        - name: AdaptiveAvgPool2d
          params:
            output_size:
            - 1
            - 1
        - name: Flatten
          params: {}
        - name: Linear
          params:
            in_features: 512
            out_features: 10

data:
  data_type: image
  target_transform:
    name: classification
    params:
      classes:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
  signal_transform:
    train-val:
    - name: Permute
      params:
        order:
          - 2
          - 0
          - 1
    - name: Rescale
      params:
        value: 255.
    - name: RandomHorizontalFlip
      params:
        p: 0.5
    - name: RandomCrop
      params:
        padding: 4
        size:
          - 32
          - 32
        padding_mode: reflect
    - name: Normalize
      params:
        mean: cifar
        std: cifar

    test:
    - name: Permute
      params:
        order:
          - 2
          - 0
          - 1
    - name: Rescale
      params:
        value: 255.
    - name: RandomHorizontalFlip
      params:
        p: 0.5
    - name: RandomCrop
      params:
        padding: 4
        size:
          - 32
          - 32
        padding_mode: reflect
    - name: Normalize
      params:
        mean: cifar
        std: cifar

  dataset:
    name: classification_dataset
    config:
      - name: CIFAR10
        version: default
    params: {}
  collate_fn:
    name: classification_collate
    params: {}
